swagger: '2.0'
info:
  description: Encontrar los productos financieros adecuado para nuevo cliente
  version: "1.0.0"
  title: ProductosFinancieros
schemes:
  - https
paths:
  /clientes:
    get:
      tags:
        - clientes
      summary: Obtener clientes registrados
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/clientes'
    post:
      tags:
        - clientes
      operationId: CrearCliente
      summary: Adiciona o actualiza información de un cliente
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: NuevoCliente
          required: true
          schema:
            $ref: '#/definitions/Clientes'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Clientes'
  /servicios:
    get:
      tags:
        - servicios
      summary: Obtener los servicios asociados a un cliente
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/ListaClienteServicio'
          headers:
            Content-Type:
              type: string
              description: Media type of request
definitions:
  clientes:
    type: array
    items:
      $ref: '#/definitions/Clientes'
  Clientes:
    type: object
    properties:
      codigo:
        type: integer
      nombre:
        type: string
      claveAcceso:
        type: string
      edad:
        type: integer
      ciudad:
        type: string
      ingreso:
        type: number
        format: double
  ListaClienteServicio:
    type: array
    items:
        $ref: '#/definitions/ClienteServicio'
  ClienteServicio:
    type: object
    properties:
      codigo:
        type: integer
      nombre:
        type: string
      servicio:
        type: string
      edad:
        type: integer
      ciudad:
        type: string
      ingreso:
        type: number
        format: double
    
